### Default config for SMFAccountValidator
### Use a YAML parser to check your syntax (http://instantyaml.appspot.com/)
### If you have any questions pm me on dev.bukkit.org or send me a mail to henno.rickowski@gmail.com
################################################################################################

# database login data
sql:
  # database to connect to
  dns: 'jdbc:mysql://localhost/smf'
  # username to login on database
  username: 'smf'
  # password to login
  password: 'password'
  # prefix for smf tables
  prefix: 'smf_'

# Set a new group/rank for validated members? 
setgroup:
  # The group/rank to set
  from: 'Gast'
  to: 'Mitglied'

messages:
  alreadyvalid: "Dein Minecraft Account ist bereits validiert."
  invalidcount: "Ungueltige Argumentanzahl."
  invalidcode: "Ungueltiger Validierungs-Code."
  validated: "Dein Minecraft Account ist nun validiert. :)"
  playeronly: "Nur Online-Spieler, nix Konsole und so."
  errorvalidate: "Unbekannter Fehler beim aktivieren des Minecraft Accounts. Bitte einen Admin kontaktieren."
