name: SMFAccountValidator
main: de.bangl.smfav.SMFAccountValidatorPlugin
version: 0.2

authors: [ BangL, mewin ]
depend: [ PermissionsEx ]

commands:
  va:
    permission: account.validate
    usage: /va [code]
    aliases: [ av, validate ]

permissions:
  account.validate:
    default: true
